name: Notify Consumer

on:
  push:
    paths:
      - 'output/fixed-token.css'
      - 'tokens.json'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Notify consumer project
        run: |
          curl -X POST https://api.github.com/repos/TirthParikh7/design-token-consumer/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.GH_PAT }}" \
            -d '{"event_type":"tokens-updated"}'
